Repository mikeleguedes/json-movie-list, pull requests merged in 2020-10, with the labels that each got.

#245 Adding Roman Holiday movie
  movies/1953/roman-holiday.json
Labels: good first issue, hacktoberfest

#246 Adding Vertido (1958) movie
  movies/1958/vertigo.json
Labels: classic movies, good first issue, hacktoberfest

#247 Add what we do in the shadows and jojo rabbit from Taika Waititi
  movies/2014/what-we-do-in-the-shadows.json
  movies/2019/jojo-rabbit.json
Labels: hacktoberfest

#236 add pacarrete to the movies list
  movies/2019/pacarrete.json
  movies/2020/never-rarely-sometimes-always.json
Labels: hacktoberfest

#248 added A thin line between love and hate in movies and Martin Lawrence…
  actors/martin-lawrence.json
  movies/1996/a-thin-line-between-love-and-hate.json
Labels: hacktoberfest

#243 Adding crip-camp.json of the movies folder
  movies/2020/crip-camp.json
Labels: hacktoberfest

#237 Create vitalina-varela.json
  movies/2019/vitalina-varela.json
Labels: hacktoberfest

#249 daniel olbrychski
  actors/daniel-olbrychski.json
Labels: directors, hacktoberfest

#250 janusz
  actors/janus-gajus.json
Labels: directors, hacktoberfest

#251 Andrzej
  actors/andrzej-seweryn.json
Labels: directors, hacktoberfest

#252 Jerzy
  actors/jerzy-stuhr.json
Labels: directors, hacktoberfest

#253 Added Man on Fire movie.
  movies/2004/man-on-fire.json
Labels: hacktoberfest

#254 Create stuck-in-love.json
  movies/2012/stuck-in-love.json
Labels: hacktoberfest

#255 Create silver-linings-playbook.json
  movies/2012/silver-linings-playbook.json
Labels: hacktoberfest

#256 Adding hocus pocus and fixing dragon
  movies/1993/dragon-the-bruce-lee-story.json
  movies/1993/hocus-pocus.json
Labels: hacktoberfest

#257 Adding Gracia Querejeta to directors collection
  directors/gracia-querejeta.json
Labels: hacktoberfest

#258 Adding Iciar Bollain to directors collection
  directors/iciar-bollain.json
Labels: hacktoberfest
